import type { Movie } from '../types/movie.types';

const IMG = {
  hero: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=1200&auto=format&fit=crop',
  action: 'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?q=80&w=900&auto=format&fit=crop',
  drama: 'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?q=80&w=900&auto=format&fit=crop',
  scifi: 'https://images.unsplash.com/photo-1518674660708-0e2c0473e68e?q=80&w=1200&auto=format&fit=crop',
  adventure: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=1200&auto=format&fit=crop',
};

export const movies: Movie[] = [
  {
    id: 'f1',
    title: 'Black Panther: Wakanda Forever',
    image: IMG.hero,
    rating: 4.8,
    genre: 'Action',
    releaseDate: 'On March 2, 2022',
    year: '2022',
    durationMinutes: 161,
    certification: 'PG-13',
    genres: ['Action', 'Movie'],
    badge: 'Premium',
    mediaType: 'Movie',
    overview:
      'The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T’Challa.',
    cast: ['Letitia Wright', 'Angela Bassett', 'Lupita Nyong’o'],
    actorIds: ['a3'],
  },
  {
    id: 'f2',
    title: 'The Way of Water',
    image: IMG.scifi,
    rating: 4.6,
    genre: 'Sci-Fi',
    releaseDate: 'On December 16, 2022',
    year: '2022',
    durationMinutes: 192,
    certification: 'PG-13',
    genres: ['Sci-Fi', 'Movie'],
    badge: 'Premium',
    mediaType: 'Movie',
    overview: 'Jake Sully lives with his newfound family on Pandora and must protect it from a familiar threat.',
    cast: ['Sam Worthington', 'Zoe Saldaña'],
    actorIds: [],
  },
  {
    id: 'f3',
    title: 'Dune: Part One',
    image: IMG.adventure,
    rating: 4.7,
    genre: 'Adventure',
    releaseDate: 'On October 22, 2021',
    year: '2021',
    durationMinutes: 155,
    certification: 'PG-13',
    genres: ['Adventure', 'Movie'],
    badge: 'Free',
    mediaType: 'Movie',
    overview: 'Paul Atreides must secure the future of his family and people on the desert planet Arrakis.',
    cast: ['Timothée Chalamet', 'Zendaya'],
    actorIds: [],
  },
  {
    id: 'p1',
    title: 'Spider-Man No..',
    image: IMG.hero,
    rating: 4.5,
    genre: 'Action',
    year: '2021',
    releaseDate: '2021',
    durationMinutes: 148,
    certification: 'PG-13',
    genres: ['Action', 'Movie'],
    badge: 'Premium',
    mediaType: 'Movie',
    overview:
      'With Spider-Man’s identity revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.',
    cast: ['Tom Holland', 'Zendaya', 'Benedict Cumberbatch'],
    actorIds: ['a1', 'a3', 'a5'],
  },
  {
    id: 'p2',
    title: 'Life of PI',
    image: IMG.action,
    rating: 4.5,
    genre: 'Action',
    year: '2012',
    releaseDate: '2012',
    durationMinutes: 127,
    certification: 'PG',
    genres: ['Adventure', 'Movie'],
    badge: 'Free',
    mediaType: 'Movie',
    overview: 'A young man survives a disaster at sea and is hurtled into an epic journey of adventure and discovery.',
    cast: ['Suraj Sharma', 'Irrfan Khan'],
    actorIds: ['a2'],
  },
  {
    id: 'p3',
    title: 'Riverdale',
    image: IMG.drama,
    rating: 4.5,
    genre: 'Action',
    year: '2021',
    releaseDate: '2021',
    durationMinutes: 45,
    certification: 'PG-13',
    genres: ['Action', 'Series'],
    badge: 'Free',
    mediaType: 'Series',
    overview: 'A subversive take on Archie and his friends exploring small-town life and the darkness bubbling beneath.',
    cast: ['KJ Apa', 'Lili Reinhart'],
    actorIds: ['a4'],
  },
  {
    id: 't1',
    title: 'Spider-Man No Way...',
    image: IMG.hero,
    rating: 4.5,
    genre: 'Action',
    year: '2021',
    releaseDate: '2021',
    durationMinutes: 148,
    certification: 'PG-13',
    genres: ['Action', 'Movie'],
    badge: 'Premium',
    mediaType: 'Movie',
    overview:
      'Peter Parker’s secret identity is revealed, forcing him to ask Doctor Strange for help — with unexpected consequences.',
    cast: ['Tom Holland', 'Zendaya'],
    actorIds: ['a5'],
  },
  {
    id: 'r1',
    title: 'The Jungle Wa..',
    image: IMG.action,
    rating: 4.5,
    genre: 'Action',
    year: '2021',
    durationMinutes: 120,
    certification: 'PG-13',
    genres: ['Action', 'Movie'],
    badge: 'Premium',
    mediaType: 'Movie',
    overview: 'An adventure through the jungle with unexpected allies and dangers.',
    actorIds: [],
  },
  {
    id: 'r2',
    title: 'Life of PI',
    image: IMG.drama,
    rating: 4.5,
    genre: 'Action',
    year: '2012',
    durationMinutes: 127,
    certification: 'PG',
    genres: ['Adventure', 'Movie'],
    badge: 'Free',
    mediaType: 'Movie',
    overview: 'A young man survives a disaster at sea and is hurtled into an epic journey of adventure and discovery.',
    actorIds: ['a2'],
  },
  {
    id: 'r3',
    title: 'Documentary',
    image: IMG.adventure,
    rating: 4.5,
    genre: 'Action',
    year: '2020',
    durationMinutes: 90,
    certification: 'PG',
    genres: ['Documentary', 'Movie'],
    badge: 'Free',
    mediaType: 'Movie',
    overview: 'A compelling documentary exploring real-world stories and insights.',
    actorIds: [],
  },
  {
    id: 'sr1',
    title: 'Spider-Man No Way...',
    image: IMG.hero,
    rating: 4.5,
    genre: 'Action',
    year: '2021',
    releaseDate: '2021',
    durationMinutes: 148,
    certification: 'PG-13',
    genres: ['Action', 'Movie'],
    badge: 'Premium',
    mediaType: 'Movie',
    overview: 'Peter Parker asks Doctor Strange to make the world forget he is Spider-Man.',
    actorIds: ['a1', 'a5'],
  },
  {
    id: 'sr2',
    title: 'Riverdale',
    image: IMG.drama,
    rating: 4.5,
    genre: 'Action',
    year: '2021',
    releaseDate: '2021',
    durationMinutes: 45,
    certification: 'PG-13',
    genres: ['Action', 'Series'],
    badge: 'Free',
    mediaType: 'Series',
    overview: 'Archie and friends face mysteries in Riverdale.',
    actorIds: ['a4'],
  },
  {
    id: 'sr3',
    title: 'Life of PI',
    image: IMG.action,
    rating: 4.5,
    genre: 'Action',
    year: '2012',
    releaseDate: '2012',
    durationMinutes: 127,
    certification: 'PG',
    genres: ['Adventure', 'Movie'],
    badge: 'Free',
    mediaType: 'Movie',
    overview: 'Survival at sea becomes a spiritual journey.',
    actorIds: ['a2'],
  },
  {
    id: 'sr4',
    title: 'The Jungle Wa..',
    image: IMG.action,
    rating: 4.5,
    genre: 'Action',
    year: '2021',
    durationMinutes: 120,
    certification: 'PG-13',
    genres: ['Action', 'Movie'],
    badge: 'Premium',
    mediaType: 'Movie',
    overview: 'Jungle expedition with high stakes.',
    actorIds: [],
  },
  {
    id: 'sr5',
    title: 'Black Panther: Wakanda Forever',
    image: IMG.hero,
    rating: 4.8,
    genre: 'Action',
    year: '2022',
    releaseDate: '2022',
    durationMinutes: 161,
    certification: 'PG-13',
    genres: ['Action', 'Movie'],
    badge: 'Premium',
    mediaType: 'Movie',
    overview: 'Wakanda faces a powerful new threat.',
    actorIds: ['a3'],
  },
];

export const featuredMovieIds = ['f1', 'f2', 'f3'];
export const popularMovieIds = ['p1', 'p2', 'p3'];
export const recommendedMovieIds = ['r1', 'r2', 'r3'];
export const todayMovieId = 't1';
